name: Lint Code Base
on:
  push:
    branches:
      - "**"
    # branches-ignore: [master]
    - "**"
  pull_request:
    branches:
      - "**"

jobs:
  lint_project:
    runs-on: ubuntu-latest
    name: A job to lint your JS projects
    steps:
      - name: Lint action step
        id: lint
        uses: chukwuemekachm/github-linter-bot@v1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
