name: Lint Code Base
on: [push, pull_request]

jobs:
  lint_project:
    runs-on: ubuntu-latest
    name: A job to lint your JS projects
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Lint action step
        id: lint
        uses: chukwuemekachm/github-linter-bot@v1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
